//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZdravaIshrana_PCL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public class Narudzbe
    {

        public Narudzbe()
        {
            this.NarudzbaStavke = new ObservableCollection<NarudzbaStavke>();
        }

        public int NarudzbaID { get; set; }

        public int SkladisteID { get; set; } //hlp
        public string BrojNarudzbe { get; set; }
        public int KupacID { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
       
        public bool Otkazano { get; set; }

        public string UdaljenostRute { get; set; }
        public string VrijemeRute { get; set; }
        public decimal IznosSaPDV { get; set; }
        public decimal IznosBezPDV { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool PayByCard { get; set; }
        public string PayByCardString { get; set; }
        public string Adresa { get; set; }
        public string Ime_i_prezime { get; set; }
        public Nullable<decimal> Iznos { get; set; }
        public Nullable<int> Broj_stavki { get; set; }
        public string DatumPrikaz { get; set; }
 



        //public string  Adresa { get; set; }
        //public int Brojstavki { get; set; }
        public decimal Ukupno { get; set; }
        public ObservableCollection<NarudzbaStavke> NarudzbaStavke { get; set; }
    }
}
