//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZdravaIshrana_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eZdravaIshrana_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicki račun već postoji..
        /// </summary>
        internal static string Acc_exist {
            get {
                return ResourceManager.GetString("Acc_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj fakture nije u ispravnom formatu dozvoljeni samo brojevi!.
        /// </summary>
        internal static string brojfakture_err {
            get {
                return ResourceManager.GetString("brojfakture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj fakture je obavezno polje!.
        /// </summary>
        internal static string brojfakture_req {
            get {
                return ResourceManager.GetString("brojfakture_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa mora imati najmanje 3 karaktera!.
        /// </summary>
        internal static string dadresa_len {
            get {
                return ResourceManager.GetString("dadresa_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezno polje..
        /// </summary>
        internal static string dadresa_req {
            get {
                return ResourceManager.GetString("dadresa_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv mora imati najmanje 3 karaktera!.
        /// </summary>
        internal static string dnaziv_len {
            get {
                return ResourceManager.GetString("dnaziv_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv je obavezno polje..
        /// </summary>
        internal static string dnaziv_req {
            get {
                return ResourceManager.GetString("dnaziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobavljac je obavezno polje!.
        /// </summary>
        internal static string dobavljac_req {
            get {
                return ResourceManager.GetString("dobavljac_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email već postoji molimo vas unesite drugi e-mail..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešan format E-mail adrese !.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email već postiji..
        /// </summary>
        internal static string email_ex {
            get {
                return ResourceManager.GetString("email_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite E-mail !.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dužina fax-a mora biti veca od 2 karaktera!.
        /// </summary>
        internal static string fax_len {
            get {
                return ResourceManager.GetString("fax_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax je obavezno polje!.
        /// </summary>
        internal static string fax_req {
            get {
                return ResourceManager.GetString("fax_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime mora sadržavati najmanje 3 slova.
        /// </summary>
        internal static string fname_len {
            get {
                return ResourceManager.GetString("fname_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime !.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt osoba je obavezno polje!.
        /// </summary>
        internal static string ko_req {
            get {
                return ResourceManager.GetString("ko_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolicina nije u ispravnom formatu!.
        /// </summary>
        internal static string kolicina_err {
            get {
                return ResourceManager.GetString("kolicina_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolicina je obavezno polje!.
        /// </summary>
        internal static string kolicina_req {
            get {
                return ResourceManager.GetString("kolicina_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite lokaciju na mapi (double click on map) !.
        /// </summary>
        internal static string LatLong_err {
            get {
                return ResourceManager.GetString("LatLong_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena lozinka ili password nisu validni!.
        /// </summary>
        internal static string login_pass_user_error {
            get {
                return ResourceManager.GetString("login_pass_user_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomena je obavezno poslje!.
        /// </summary>
        internal static string nap_req {
            get {
                return ResourceManager.GetString("nap_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime nema dovoljno karaktera !.
        /// </summary>
        internal static string naziv_len {
            get {
                return ResourceManager.GetString("naziv_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas unesite ime i prezime !.
        /// </summary>
        internal static string naziv_req {
            get {
                return ResourceManager.GetString("naziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis je obavezno polje!.
        /// </summary>
        internal static string opis_req {
            get {
                return ResourceManager.GetString("opis_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju !!!.
        /// </summary>
        internal static string pass_dismatch {
            get {
                return ResourceManager.GetString("pass_dismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati najmanje 3 charaktera!.
        /// </summary>
        internal static string pass_len {
            get {
                return ResourceManager.GetString("pass_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje!.
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema slike u bazi molimo dodajte je!.
        /// </summary>
        internal static string pbaz_req {
            get {
                return ResourceManager.GetString("pbaz_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena nije u ispravnom formatu!.
        /// </summary>
        internal static string pcijena_err {
            get {
                return ResourceManager.GetString("pcijena_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena je obavezno polje!.
        /// </summary>
        internal static string pcijena_req {
            get {
                return ResourceManager.GetString("pcijena_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdv nije u ispravnom formatu!.
        /// </summary>
        internal static string pdv_err {
            get {
                return ResourceManager.GetString("pdv_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdv je obavezno polje.
        /// </summary>
        internal static string pdv_req {
            get {
                return ResourceManager.GetString("pdv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimenzije slike moraju biti  veće od 120x120!.
        /// </summary>
        internal static string picture_size {
            get {
                return ResourceManager.GetString("picture_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika nije u prihvatiljivoj velicini!.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv proizvoda mora sadržavati najmanje 3 karaktera!.
        /// </summary>
        internal static string pname_len {
            get {
                return ResourceManager.GetString("pname_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv proizvoda je obavezno polje!.
        /// </summary>
        internal static string pname_req {
            get {
                return ResourceManager.GetString("pname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odabrati jednog Proizvođača!.
        /// </summary>
        internal static string pproi_req {
            get {
                return ResourceManager.GetString("pproi_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra mora imati najmanje 3 karaktera!.
        /// </summary>
        internal static string psif_len {
            get {
                return ResourceManager.GetString("psif_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra je obavezno polje!.
        /// </summary>
        internal static string psif_req {
            get {
                return ResourceManager.GetString("psif_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je obavezna!.
        /// </summary>
        internal static string psli_req {
            get {
                return ResourceManager.GetString("psli_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite sortu!.
        /// </summary>
        internal static string psor_req {
            get {
                return ResourceManager.GetString("psor_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite vrstu!.
        /// </summary>
        internal static string pvrs_req {
            get {
                return ResourceManager.GetString("pvrs_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladiste je obavezno polje.
        /// </summary>
        internal static string skladiste_req {
            get {
                return ResourceManager.GetString("skladiste_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime mora sadržavatri najmanje 3 slova.
        /// </summary>
        internal static string sname_len {
            get {
                return ResourceManager.GetString("sname_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje!.
        /// </summary>
        internal static string sname_req {
            get {
                return ResourceManager.GetString("sname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje sorta je obavezno..
        /// </summary>
        internal static string sortaobavezna {
            get {
                return ResourceManager.GetString("sortaobavezna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ova sorta već postoji..
        /// </summary>
        internal static string sortapostoji {
            get {
                return ResourceManager.GetString("sortapostoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozvoljeni znakovi su ( . @ - _ ) .
        /// </summary>
        internal static string string_sc {
            get {
                return ResourceManager.GetString("string_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dozvoljeni znakovi su ( .  - _ ).
        /// </summary>
        internal static string string_scACC {
            get {
                return ResourceManager.GetString("string_scACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nije u ispravnom formatu!.
        /// </summary>
        internal static string tel_len {
            get {
                return ResourceManager.GetString("tel_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezno polje!.
        /// </summary>
        internal static string tel_req {
            get {
                return ResourceManager.GetString("tel_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite barem jednu ulogu!.
        /// </summary>
        internal static string uloge_req {
            get {
                return ResourceManager.GetString("uloge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime već postoji molimo vas unesite drugo korisničko ime.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime mora imati najmanje 3 karaktera!.
        /// </summary>
        internal static string username_len {
            get {
                return ResourceManager.GetString("username_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krosnicko ime je obavezno poslje!.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje !.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web je obavezno polje !!!.
        /// </summary>
        internal static string web_req {
            get {
                return ResourceManager.GetString("web_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziro racun treba da sadrzi 18 brojeva!.
        /// </summary>
        internal static string zir_len {
            get {
                return ResourceManager.GetString("zir_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziro racun je obavezno polje!.
        /// </summary>
        internal static string zir_req {
            get {
                return ResourceManager.GetString("zir_req", resourceCulture);
            }
        }
    }
}
