//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZdravaIshrana_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbalazaStavke
    {
        public int AmbalazaStavkaID { get; set; }
        public int Kolicina { get; set; }
        public Nullable<int> KupacID { get; set; }
        public Nullable<int> DostavljacID { get; set; }
        public Nullable<int> AmbalazaID { get; set; }
        public Nullable<int> IzlazID { get; set; }
    
        public virtual Ambalaza Ambalaza { get; set; }
        public virtual Izlazi Izlazi { get; set; }
        public virtual Dostavljaci Dostavljaci { get; set; }
        public virtual Kupci Kupci { get; set; }
    }
}
